jobs:
  - name: itrust-build
    repo: https://{{username}}:{{token}}@github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git
    build:
      setup: # NEW
        - name: Build environment
          steps:
            - name: Setup & Updates
              run: 'sudo apt-get update -yqq && sudo apt-get upgrade -yqq'
            - name: Install Dependencies
              run: 'sudo apt-get install -yqq python3-pip openjdk-11-jdk git maven docker.io'
      steps:
        - name: Setup MySql
          run: 'sudo docker run --name mysql --network host -e MYSQL_ROOT_PASSWORD={{root_pass}} -d mysql:8.0'
        - name: Copy application.yml file
          run: 'cp {{job_loc}}/iTrust2/src/main/resources/application.yml.template {{job_loc}}/iTrust2/src/main/resources/application.yml'
        - name: Copy database password into application.yml file
          run: 'sudo sed -i "s/password\:/password\:\ {{root_pass}}/g" {{job_loc}}/iTrust2/src/main/resources/application.yml'
        - name: Build iTrust
          run: 'cd {{job_loc}}/iTrust2/ && mvn --batch-mode --update-snapshots clean test'
        - name: Create jar file for deployment
          run: 'cd {{job_loc}}/iTrust2/ && mvn package'
  - name: itrust-deploy
    deploy:
      type: green-blue
      provider: azure
      inventory: 'inventory'
      artifacts:
        - source: '~/itrust-build/iTrust2/target/iTrust2-10.jar'
          dest: '~/iTrust2-10.jar'
      steps:
        - name: Run iTrust2
          run: 'java -jar ~/iTrust2-10.jar'
  - name: mutation-coverage
    repo: https://github.com/chrisparnin/checkbox.io-micro-preview
    build:
      steps:
        - name: Mutation Testing
          mutation:
            mutate:
              - 'marqdown.js'
            iterations: 1000
            init: 'npm install'
            snapshot:
              run: 'node index.js'
              collect:
                - 'http://localhost:3000/survey/long.md'
                - 'http://localhost:3000/survey/upload.md'
                - 'http://localhost:3000/survey/survey.md'
                - 'http://localhost:3000/survey/variations.md'
  - name: focalboard
    repo: https://github.com/mattermost/focalboard.git
    build:
      setup:
        - name: install dependencies
          steps:
            - name: add golang repo
              run: 'sudo add-apt-repository ppa:longsleep/golang-backports'
            - name: setup & updates
              run: 'sudo apt-get update -y'
            - name: install make & go
              run: 'sudo apt-get install -y make golang-go'
            - name: check version # debugging
              run: 'go version'
      steps:
        - name: prebuild
          run: 'cd {{job_loc}} && make prebuild'
        - name: build
          run: 'cd {{job_loc}} && make'
        - name: check build worked
          run: 'cd {{job_loc}} && ./bin/focalboard-server'