setup:
  - name: env
    steps:
      - name: env1
        run: 'echo "env1"'
  - name: file
    steps:
      - name: file1
        run: 'echo "file1"'
  - name: packages
    steps:
      - name: update
        run: 'apt-get update'
      - name: pip
        run: 'apt-get install python3-pip'
      - name: jdk 11
        run: 'apt-get install openjdk-11-jdk -y'
  - name: docker
    steps:
      - name: engine
        run: 'apt-get install docker-ce docker-ce-cli containerd.io'
      - name: image
        run: 'docker pull ubuntu:20.04'

jobs:
  - name: Job1
    steps:
      - name: Step1
        run: 'echo "step1 running"'
      - name: Step2
        run: 'echo "step2 running"'
  - name: Job2
    steps:
      - name: Step3
        run: 'echo "step3 running"'
      - name: Step4
        run: 'echo "step4 running"'