setup:
  - name: build environment
    steps:
      - name: Update
        run: 'apt-get update -yqq'
      - name: Install Dependencies
        run: 'apt-get install -yqq python3-pip openjdk-11-jdk git maven'

jobs:
  - name: iTrust
    repo: https://{{username}}:{{password}}@github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git
    steps:
      - name: Setup iTrust
        run: |
          cp /iTrust2/src/main/resources/application.yml.template /iTrust2/src/main/resources/application.yml \
          && /bakerx/reference/add_password.sh
      - name: Build iTrust
        run: 'mvn -q spring-boot:run'
