setup:
  - name: build environment
    steps:
      # - name: build dockerfile to setup docker image
      #   run: 'sudo docker build -t p:latest - < /bakerx/Dockerfile'
      - name: run docker build container
        run: 'sudo docker run -d -v /bakerx:/bakerx --name itrust --network host p:latest sleep infinity'
      - name: run docker mysql container
        run: 'pass=$(grep -oP "root_pass:\s+\K\w+" /bakerx/.env) && sudo docker run --name mysql --network host -e MYSQL_ROOT_PASSWORD=$pass -d mysql:8.0'

jobs:
  - name: Copy iTrust
    steps:
      - name: make folder
        run: 'sudo docker exec itrust mkdir iTrust2'
      - name: copy iTrust
        run: 'sudo docker exec itrust cp -RT /bakerx/reference/iTrust2 /iTrust2'
  - name: Setup iTrust
    steps:
      - name: rename YAML file
        run: 'sudo docker exec itrust cp /iTrust2/src/main/resources/application.yml.template /iTrust2/src/main/resources/application.yml'
      - name: configure application.yml file
        run: 'sudo docker exec itrust /bakerx/reference/add_password.sh'
  - name: Build iTrust
    steps:
      - name: build
        run: 'sudo docker exec -w /iTrust2 itrust mvn -q spring-boot:run'